### ISSUE TITLE
Post-Fix, plugin still breaks

### ISSUE THREAD

**Issue by OriginalUsernameLMAO** [Loze-Put/hunllef-helper#18] opened 2022-02-10 13:36 UTC
I got trampled and hit the button, that's where I think I recreated the audio issue. It said "...1..." and nothing else. Wanted to keep testing so I didn't reset it. Next it said "2, 1..." nothing, and continued to be messed up for 2 more attack changes. BUT I did immediately get trampled b2b after the first trample. After clicking reset and starting again it worked throughout the kill.

**Comment by Fauxbear95** [comment] 2022-03-03 19:24
It's still just not working properly for me. I just did my first run in about a month since I was previously posting in the other thread and I'm experiencing the exact same problems. Also, for me the issue was happening without having clicked the trample button.

**Comment by Loze-Put** [comment] 2022-06-21 17:50
Closing this as it is a duplicate of #16

**Closed as completed by Loze-Put** 2022-06-21 17:50 UTC
