### ISSUE TITLE
Custom sounds not working

### ISSUE THREAD

**Issue by TmScape** [Loze-Put/hunllef-helper#21] opened 2022-06-26 18:24 UTC
Hello,

I tried to follow the guide to create custom sound with no success. Is it possible to make a video of the method? Is it still working?

Thanks

**Comment by TmScape** [comment] 2022-06-26 19:03
> Hello,
> 
> I tried to follow the guide to create custom sound with no success. Is it possible to make a video of the method? Is it still working?
> 
> Thanks

The sound of mage and range audio cures are quite similar sounding and therefore I get mixed up when hunlef takes of my prayer which prayer to put back on.

**Comment by Loze-Put** [comment] 2022-06-27 11:29
Hi,

Here is a little list of things to check:
- Are your audio files `wav` files? Renaming the files does not convert them to a different format. If your original files have a different format you can convert them using some online service. For instance, search for `mp4 to wav` online.

- Are your files in the right directory? The files should be within an audio folder inside your .runelite folder. The path on Windows is `Disk:\Users\Username\.runelite\audio` by default.

- Do the files match the required names (`mage.wav`, `range.wav`, `one.wav` and `two.wav`)?

- Have you set the `Audio Mode` in the plugin configuration to `Custom`?


> The sound of mage and range audio cures are quite similar sounding and therefore I get mixed up when hunlef takes of my prayer which prayer to put back on.

Hunllef can only use the reset prayer attack instead of a magic attack. If the attack is used instead of the last magic attack, you will hear `ranged` from the plugin. Otherwise you should always turn the protect from magic prayer on.

**Comment by TmScape** [comment] 2022-06-27 16:48
I have done all of the above. Can I show you my screen on discord, please? Shoocane#2279

**Comment by Loze-Put** [comment] 2022-06-28 18:59
The issue has been resolved via Discord. Information for anyone else with the same issue:

Windows file explorer has an option to hide file extensions. Renaming a file to the required names will create a double extension in the file name which is not visible. A file will look like it's called `mage.wav`, but it's actually called `mage.wav.wav`. One way to resolve this issue is to enable file extensions in the file explorer. Another way to resolve the issue is to remove the file extension and see if the file can still be opened by any media application.

**Closed as completed by Loze-Put** 2022-06-28 18:59 UTC
