### ISSUE TITLE
Plugin needs update

### ISSUE THREAD

**Issue by OGSIMBA23** [Loze-Put/hunllef-helper#44] opened 2024-01-14 21:51 UTC
Plug-in currently not working due to needing an update.

**Comment by tuckerMEDSkevin** [comment] 2024-01-14 23:11
I think that's what #43 is about. The author is aware.

**Comment by Loze-Put** [comment] 2024-01-15 07:48
Thanks for the notification. This is however a duplicate of #43, so I will close this issue.

**Closed as completed by Loze-Put** 2024-01-15 07:48 UTC
