### ISSUE TITLE
Audio cuts out

### ISSUE THREAD

**Issue by Fauxbear95** [Loze-Put/hunllef-helper#16] opened 2022-02-05 16:30 UTC
From time to time it seems like the audio is cutting out. Sometimes it's just some of the countdown but other times it's the full countdown and call to change prayer which has resulted in me taking a hit. I know I shouldn't be fully relying on the audio and don't blame the plugin but I thought you should know.

**Comment by jprice435** [comment] 2022-02-05 21:46
Having the same issue as well. Seems to be random and happened on multiple pcs. Audio will skip countdowns or not work at all

**Comment by observnad** [comment] 2022-02-06 18:24
My favorite is when it just says "2" and nothing else :)

**Comment by observnad** [comment] 2022-02-06 19:03
I tested using custom audio and it still randomly fails to play audio files. To make the issue more clear, what we are experiencing is one or more of the audio files does not get played at all. So we might only here "2" "" "", or maybe "2" "" "mage", and sometimes nothing, but i havn't experienced that yet.

**Comment by Fauxbear95** [comment] 2022-02-06 19:21
I have experienced when it doesn't play anything. It's rare but happens.

**Comment by Loze-Put** [comment] 2022-02-07 07:51
I am aware of this issue that occurs since the latest update of the plugin. The most difficult part about fixing it is that it is nearly impossible to reproduce. I am working on a fix but testing the fixes can easily take a few hours per attempt.

**Comment by jprice435** [comment] 2022-02-07 17:41
Any way for us to try and give you more data to help?

**Comment by Fauxbear95** [comment] 2022-02-07 18:37
I agree, I'm running the CG right now so if you update us when you push fixes I'll let you know if I'm running into those issues still.

**Comment by edgar-martinez** [comment] 2022-02-09 02:53
Any chance you could revert to the previous commit while the issue is resolved? I could do without the custom audio feature.

Not sure if it helps but here's some info. 

Client Specifications:
- Runelite version: 1.8.10
- Oldschool revision: Rev 202
- Launcher version: 2.2.0

Windows Specifications:
- Edition: Windows 10
- Version: 21H2
- OS build: 19044.1466

**Comment by SupahSoftware** [comment] 2022-02-09 22:29
+1 having this exact issue as well. Both with default and custom audio

**Comment by Loze-Put** [comment] 2022-02-13 18:31
The plugin has been updated. Please let me know if the issue still occurs.

**Comment by VAELLLL** [comment] 2022-02-15 17:50
Just downloaded the plugin yesterday, I've done about 50 runs and I'd say the issue occurs at minimum once per fight, but it's usually multiple times. Appreciate the time and effort you're putting into an invaluable plugin

Edit: Turned off all in game sounds, seems to have fixed it. Not ideal though so maybe that can give an idea of where to find a res

**Comment by edgar-martinez** [comment] 2022-05-13 03:24
@Loze-Put  This is still happening. Any chance you would consider reverting pre-custom sounds?

**Comment by Loze-Put** [comment] 2022-08-04 08:17
Another attempt to resolve this issue has been published. Could anyone check if this issue still occurs?

**Comment by VAELLLL** [comment] 2022-08-17 14:47
I will try to check in the coming week, buried in work at the moment

**Comment by jprice435** [comment] 2022-08-17 20:03
Ive recently spent a few hours in cg and have not had the issue occur

**Comment by Loze-Put** [comment] 2022-08-30 12:56
I have not received any reports of the issue still occurring.  I'll close this for now.

**Closed as completed by Loze-Put** 2022-08-30 12:56 UTC
